sudo: required

services:
  - docker

before_install:
  - docker image build -t bkouhen/docker-angular-client-test -f Dockerfile.dev .

script:
  - docker run bkouhen/docker-angular-client-test npm run test:ci
  - docker run bkouhen/docker-angular-client-test npm run e2e:ci

after_success:
  - docker image build -t bkouhen/docker-angular-client .
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bkouhen/docker-angular-client

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-west-3"
#   app: "docker-angular"
#   env: "DockerAngular-env"
#   bucket_name: "elasticbeanstalk-eu-west-3-804229121763"
#   bucket_path: "docker-angular"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY_ID
#   secret_access_key: $AWS_SECRET_ACCESS_KEY

