sudo: required

services:
  - docker

before_install:
  - docker image build -t bkouhen/docker-angular-client -f Dockerfile.dev .

script:
  - docker run bkouhen/docker-angular-client npm run test:ci
  - docker run bkouhen/docker-angular-client npm run e2e:ci

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-angular"
  env: "DockerAngular-env"
  bucket_name: "elasticbeanstalk-eu-west-3-804229121763"
  bucket_path: "docker-angular"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

