version: '3'

services:
  web:
    image: angular-client
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
  tests:
    image: angular-client
    depends_on:
      - web
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: ["npm", "run", "test:ci"]
  e2e:
    image: angular-client
    depends_on:
      - web
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: ["npm", "run", "e2e:ci"]
